package com.steelezide.nethys.dtos;

import com.steelezide.nethys.pojos.PreparedSpell;
import com.steelezide.nethys.pojos.Spellcaster;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PreparedSpellDto {
    
    /**
     * ID auto-generated by the database used to reference a specific prepared spell.
     */
    private int id;

    /**
     * Denotes the spell that has been prepared. This spell will be null
     * if no spell is prepared for this slot. 
     */
    private SpellDto spell;

    /**
     * If true, the slot this spell is assigned to has been used. Cantrips
     * will always be false.
     */
    private Boolean casted;

    public PreparedSpellDto(PreparedSpell preparedSpell){
        this();
        this.id = preparedSpell.getId();
        this.casted = preparedSpell.getCasted();
        this.spell = new SpellDto(preparedSpell.getSpell());
    }

    public PreparedSpell toPojo(Spellcaster owner) {

        PreparedSpell ps = new PreparedSpell(
            this.getId(),
            owner,
            this.getSpell().toPojo(),
            this.getCasted()
        );
        
        return ps;
    }
}
