package com.steelezide.nethys.dtos;

import com.steelezide.nethys.pojos.Spell;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class SpellDto {

    /**
     * ID auto-generated by the database used to reference a specific spell.
     */
    private int id;

    private String name;
    
    private int level;
    
    /**
     * The school of magic this spell derives from. 
     * <p> Examples: 
     * <ul>
     * <li>"Conjuration" </li>
     * <li>"Divination", etc.</li>
     * </ul>
     */
    private String school;
    
    /**
     * Type denotes the parent type of magic that this spell derives from.
     * Example: "Divine", "Arcane", etc.
     */
    private String type;
    
    /**
     * Represents the time it takes to cast a spell per the games mechanics.
     * <p> Examples: 
     * <ul>
     * <li>"1 standard action"</li>
     * <li>"1 round" etc.</li>
     * </ul>
     */
    private String castTime;
    
    /**
     * Represents the components required to cast a spell per the games mechanics.
     * <p> Examples: 
     * <ul>
     * <li>"V, S, M(diamond worth 10,000 gp), DF" </li>
     * <li>"V, S, F", etc.</li>
     * </ul> 
     */
    private String components;
    
    /**
     * Represent the range at which a spell can be cast.
     * <p> Examples: 
     * <ul>
     * <li>"close (25 ft. + 5 ft./2 levels)"</li>
     * <li>"touch", etc.</li>
     * </ul>
     */
    private String range;
    
    /**
     * Represents the recipient(s) of this spell.
     * <p> Examples: 
     * <ul>
     * <li>"one creature/level, no two of which can be more than 30 ft. apart" </li>
     * <li>"creature touched" </li> 
     * <li>"long (400 ft. + 40 ft./level)" </li> 
     * <li>"15 ft.", etc. </li> 
     * </ul>
     */
    private String target;
    
    /**
     * Represent the area of effect for this spell.
     * <p> Examples: 
     * <ul>
     * <li>"20-ft.-radius spread"</li>
     * <li>"cone-shaped burst", etc.</li>
     * </ul>
     */
    private String area;

    /**
     * Represents the amount of time the spell last in game mechanics.
     * <p> Examples: 
     * <ul>
     * <li>"instantaneous"</li>
     * <li>"1 min./level"</li>
     * <li>"concentration, up to 1 min./level (D)"</li>
     * <li>"1 round/level", etc.</li>
     * </ul>
     */
    private String duration;
    
    /**
     * Represents the saving throw for this spell.
     * <p> Examples: 
     * <ul>
     * <li>"none"</li>
     * <li>"Reflex half"</li>
     * <li>"Will negates", etc.</li>
     * </ul>  
     */
    private String savingThrow;
    
    /**
     * If true, this spell can be effected by a target's resistance to spells.
     */
    private boolean spellResistance;
    
    private String description;

	public SpellDto(Spell spell) {
        this();
        this.id = spell.getId();
        this.name = spell.getName();
        this.level = spell.getLevel();
        this.school = spell.getSchool();
        this.type = spell.getType();
        this.castTime = spell.getCastTime();
        this.components = spell.getComponents();
        this.range = spell.getRange();
        this.target = spell.getTarget();
        this.area = spell.getArea();
        this.duration = spell.getDuration();
        this.savingThrow = spell.getSavingThrow();
        this.spellResistance = spell.isSpellResistance();
        this.description = spell.getDescription();
	}

	public Spell toPojo() {

        Spell spell = new Spell(
            this.getId(),
            this.getName(),
            this.getLevel(),
            this.getSchool(),
            this.getType(),
            this.getCastTime(),
            this.getComponents(),
            this.getRange(),
            this.getTarget(),
            this.getArea(),
            this.getDuration(),
            this.getSavingThrow(),
            this.isSpellResistance(),
            this.getDescription()
        );

		return spell;
	} 
}
