spring:
    datasource:
        url: ${nethys_url}
        username: ${nethys_username}
        password: ${nethys_password}
        driverClassName: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: ${nethys_show-sql:false}
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
