package com.steelezide.nethys.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This class represents a {@link Spell} assigned to a character's spell slot.
 * 
 */
@Entity
@Table(name = "prepared_spell")
@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator.class,
    property = "id")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PreparedSpell {

    /**
     * ID auto-generated by the database used to reference a specific prepared spell.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    /**
     * Denotes the character who has prepared this spell.
     */
    @ManyToOne
    @JoinColumn(name = "char_id")
    private Spellcaster owner;

    /**
     * Denotes the spell that has been prepared. This spell will be null
     * if no spell is prepared for this slot. 
     */
    @ManyToOne
    @JoinColumn(name = "spell_id")
    private Spell spell;

    /**
     * If true, the slot this spell is assigned to has been used. Cantrips
     * will always be false.
     */
    @Column(name = "casted")
    private Boolean casted;
    
}
