package com.steelezide.nethys.pojos;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.persistence.Id;
import javax.persistence.Column;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * An object that contains the data representing a Pathfinder 1st edition spell.
 * Has a no-args and all args constructor. 
 */
@Entity
@Table(name = "spell")
@JsonIdentityInfo(
    generator = ObjectIdGenerators.PropertyGenerator.class,
    property = "id")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Spell {
    
    /**
     * ID auto-generated by the database used to reference a specific spell.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "name")
    private String name;
    
    @Column(name = "level")
    private int level;
    
    /**
     * The school of magic this spell derives from. 
     * <p> Examples: 
     * <ul>
     * <li>"Conjuration" </li>
     * <li>"Divination", etc.</li>
     * </ul>
     */
    @Column(name = "school")
    private String school;
    
    /**
     * Type denotes the parent type of magic that this spell derives from.
     * Example: "Divine", "Arcane", etc.
     */
    @Column(name = "type")
    private String type;
    
    /**
     * Represents the time it takes to cast a spell per the games mechanics.
     * <p> Examples: 
     * <ul>
     * <li>"1 standard action"</li>
     * <li>"1 round" etc.</li>
     * </ul>
     */
    @Column(name = "cast_time")
    private String castTime;
    
    /**
     * Represents the components required to cast a spell per the games mechanics.
     * <p> Examples: 
     * <ul>
     * <li>"V, S, M(diamond worth 10,000 gp), DF" </li>
     * <li>"V, S, F", etc.</li>
     * </ul> 
     */
    @Column(name = "components")
    private String components;
    
    /**
     * Represent the range at which a spell can be cast.
     * <p> Examples: 
     * <ul>
     * <li>"close (25 ft. + 5 ft./2 levels)"</li>
     * <li>"touch", etc.</li>
     * </ul>
     */
    @Column(name = "range")
    private String range;
    
    /**
     * Represents the recipient(s) of this spell.
     * <p> Examples: 
     * <ul>
     * <li>"one creature/level, no two of which can be more than 30 ft. apart" </li>
     * <li>"creature touched" </li> 
     * <li>"long (400 ft. + 40 ft./level)" </li> 
     * <li>"15 ft.", etc. </li> 
     * </ul>
     */
    @Column(name = "target")
    private String target;
    
    /**
     * Represent the area of effect for this spell.
     * <p> Examples: 
     * <ul>
     * <li>"20-ft.-radius spread"</li>
     * <li>"cone-shaped burst", etc.</li>
     * </ul>
     */
    @Column(name = "area")
    private String area;

    /**
     * Represents the amount of time the spell last in game mechanics.
     * <p> Examples: 
     * <ul>
     * <li>"instantaneous"</li>
     * <li>"1 min./level"</li>
     * <li>"concentration, up to 1 min./level (D)"</li>
     * <li>"1 round/level", etc.</li>
     * </ul>
     */
    @Column(name = "duration")
    private String duration;
    
    /**
     * Represents the saving throw for this spell.
     * <p> Examples: 
     * <ul>
     * <li>"none"</li>
     * <li>"Reflex half"</li>
     * <li>"Will negates", etc.</li>
     * </ul>  
     */
    @Column(name = "saving_throw")
    private String savingThrow;
    
    /**
     * If true, this spell can be effected by a target's resistance to spells.
     */
    @Column(name = "spell_resistance")
    private boolean spellResistance;
    
    @Column(name = "description")
    private String description;
}
